# experiment options
output_dir: outputs/train
exp_name: len_64_k_15_trajectory

# logger options
debug: false
max_iter: 1000000              # maximum number of training iterations
validation_iter: 50000
visualize_iter: 50000       # How often do you want to save output images during training
snapshot_save_iter: 50000      # How often do you want to save trained models
pred_vibe_iter: 50000
log_iter: 50                   # How often do you want to log the training stats

# optimization options
weight_decay: 0.0001          # weight decay
lr: 0.0001                # learning rate for the generator
lr_policy: step
step_size: 100000
gamma: 0.3
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]

# loss weight
rec_root_v_w: 10000
rec_absolute_rot_pos_w: 1
rec_absolute_velocity: 1000
rec_absolute_acceleration: 100000
contact_w: 10000
# kl_w: 0.003

# contact
pos_height_thresh: 0.045
velocity_thresh: 0.1

# dataloader
train_batch_size: 64
val_batch_size: 16
test_batch_size: 1
num_workers: 2

# model options
train_seq_len: 64
overlap: 0.95
kernel_size: 15
latent_d: 24
n_joints: 24    
num_layers: 4          
extra_conv: 0
skeleton_dist: 2
skeleton_pool: mean
padding_mode: reflection
upsampling: linear
encoder_channel_base: 4

# dataset options
db_dir: /data/jsy/datasets/AMASS/db_lib
mean_std_path: data/for_all_data_motion_model/all_amass_data_mean_std.npy
refined_vibe_data_dir: /data/jsy/code/hm-vae/outputs/train/len_8_k_3_no_aug_mae/20220430212924-len_8_k_3_no_aug_mae/images/500000/refined_rot_mat

parent_json_file: utils/data/joint24_parents.json

vibe_data_dir: /data/jsy/code/VIBE/output
video_list:
  - sample_video.ma4
  - hiphop_clip1.mp4
  - downtown_walkUphill_00.mp4
  - outdoors_fencing_01.mp4
  - outdoors_freestyle_01.mp4
  - downtown_weeklyMarket_00.mp4

# render
tmp_rendered_image_folder: "" # ouput_dir/tmp
resolution: [1280, 1280]
